// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_check.sql

package db

import (
	"context"
)

const dB_PING = `-- name: DB_PING :exec
SELECT 1
`

func (q *Queries) DB_PING(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dB_PING)
	return err
}
