// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, bucket_name, image_key, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, bucket_name, image_key, status, created_at, updated_at
`

type CreateImageParams struct {
	UserID     pgtype.Int4      `json:"user_id"`
	BucketName string           `json:"bucket_name"`
	ImageKey   string           `json:"image_key"`
	Status     pgtype.Text      `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.BucketName,
		arg.ImageKey,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BucketName,
		&i.ImageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, created_at)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.CreatedAt)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, user_id, bucket_name, image_key, status, created_at, updated_at
FROM images
WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id int32) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BucketName,
		&i.ImageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImagesByUserID = `-- name: GetImagesByUserID :many
SELECT id, user_id, bucket_name, image_key, status, created_at, updated_at
FROM images
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetImagesByUserID(ctx context.Context, userID pgtype.Int4) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BucketName,
			&i.ImageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at 
FROM users 
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const updateImageStatus = `-- name: UpdateImageStatus :exec
UPDATE images 
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateImageStatusParams struct {
	Status    pgtype.Text      `json:"status"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ID        int32            `json:"id"`
}

func (q *Queries) UpdateImageStatus(ctx context.Context, arg UpdateImageStatusParams) error {
	_, err := q.db.Exec(ctx, updateImageStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
