// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID         int32            `json:"id"`
	UserID     pgtype.Int4      `json:"user_id"`
	BucketName string           `json:"bucket_name"`
	ImageKey   string           `json:"image_key"`
	Status     pgtype.Text      `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
